version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  aws-cli: circleci/aws-cli@1.0.0

terraform: &terraform
  docker:
    - image: hashicorp/terraform:light
  working_directory: /tmp/workspace/terraform


jobs:
  build:
    <<: *terraform
    environment:
      BASH: true
    steps:
      - checkout
      - run:
          name: install curl bash
          command: apk update && apk add curl curl-dev bash
      - run:
          name: terraform init
          command: terraform init -backend-config=backend.hcl
      - run:
          name: terraform validate
          command: terraform validate
      - run:
          name: terraform plan
          command: terraform plan -input=false
      - run:
          name: terraform apply -auto-approve
          command: terraform apply -auto-approve
      - run:
          name: terraform destroy
          command: terraform destroy -auto-approve
      - slack/status:
          fail_only: false
          mentions: 'ayobuba'
          only_for_branches: 'dev'
          webhook: 'https://hooks.slack.com/services/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'

  aws-cli-configure:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: superhero
      - run:
          name: List VPC's
          command: aws ec2 describe-vpcs




# configure context for project and configure slack hooks for project
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: prenovate-context
      - aws-cli-configure:
          context: prenovate-context
          requires:
            - build
